spring:
  application:
    name: befresh
#  threads:
#    virtual:
#      enabled: true

  config:
    import:
      - application-datasource.yml
      - application-server.yml
      - application-fcm.yml
      - application-jwt.yml